idf_component_register(SRCS "app_main.cpp"
                            "frontend.cpp"
                            "spoofer.cpp"
                            "utm.cpp"
                            "id_open.cpp"
                            "id_open_esp32.cpp"
                            "id_open_china.cpp"
                            "opendroneid.c"
                            "wifi.c"
                            "alt_unix_time.c"
                            "id_open_beacon.cpp"
                    INCLUDE_DIRS ".")